name: GitHub Pages

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: chmod +x ./gradlew
      - name: generate site
        run: ./gradlew generateIndex bake --info --stacktrace
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/html5/site
